baseurl = "https://ngsanogo.com/"
languageCode = "en-US"
title = "Issa Sanogo"
disqusShortname = "ngsanogo"
googleAnalytics = "UA-114981879-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
theme = "hugo-sustain"
enableEmoji = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "N'Gouro dit Issa Sanogo"
  description = "This is my personnel website."

  custom_css = []
  custom_js  = []

[params.social]
  Github        = "ngsanogo"
  Email         = "ngsanogo@gmail.com"
  Twitter       = "ngsanogo"
  LinkedIn      = "ngsanogo"

## Main Menu
[[menu.main]]
  name = "about"
  identifier = "about"
  weight = 1
  url = "/about/"
[[menu.main]]
  name = "blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 3
  url = "/projects/"
[[menu.main]]
  name = "teaching"
  identifier = "teaching"
  weight = 4
  url = "/teaching/"
[[menu.main]]
  name = "consulting"
  identifier = "consulting"
  weight = 5
  url = "/consulting/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 6
  url = "/resume/"
[[menu.main]]
  name = "contact"
  identifier = "contact"
  weight = 7
  url = "/contact/"
