---
title: "Resume"
output: html_document
---
```{r, echo = FALSE, warning = FALSE, message = FALSE, results = 'hide'}
Sys.setlocale("LC_TIME", "C")
```

Pulblished: April 15, 2018  
Last update: `r Hmisc::capitalize(format(Sys.Date(), '%B %d, %Y'))`


## Contact information

+ Email: [ngsanogo@gmail.com](ngsanogo@gmail.com)

+ LinkdIn: [Issa Sanogo](https://www.linkedin.com/in/ngsanogo/)

+ Twitter: [ngsanogo](https://twitter.com/ngsanogo)

+ Adress: <a href= "https://www.google.fr/maps/place/92150+Suresnes/data=!4m2!3m1!1s0x47e664c5b40ecee7:0x1c0b82c6e1d88150?sa=X&ved=0ahUKEwjT_JDfjurZAhUP2qQKHSRCAgcQ8gEILTAA" target = "_blank">Suresnes, 92150, France</a>

## Short biography

I am [Issa Sanogo](https://www.ngsanogo.com/), I am malian.  
I am a huge nerd passioned by data science. I love learning and teaching. I am in favor of popularizing sience.  
After beeing graduated of bachelor's degree in Mali I came in France to do my graduate studies. I graduated from <a href= "http://www.mi.parisdescartes.fr/" target = "_blank">UFR Math-Info Université Paris DESCARTES</a>, where I obtained a M.S. in mathematical engineering applied to life sciences.

Now, I am working at <a href= "https://aphp.fr" target = "_blank">APHP</a> as a data manager.

I am pretty much an **useR** and a big fan of open source software.

## Education

+ Master's degree in mathematical engineering applied to life sciences at <a href= "http://www.mi.parisdescartes.fr/" target = "_blank">UFR Math-Info Université Paris DESCARTES</a>, France

+ Bachelor's degree in science at Lycée Soundiata Keita, Mali.

## Professional Experience

+ **Data manager at <a href= "https://aphp.fr" target = "_blank">APHP</a>** from 01/09/2017 to now  
Development of algorithm in R of consistency check, creation of database (CleanWeb), reporting with R and development of application (Shiny).

+ **Internship as data manager at <a href= "https://aphp.fr" target = "_blank">APHP</a>** from 15/02/2017 to 15/08/2017  
Development of algorithm in R of consistency check, creation of database (CleanWeb), reporting with R.

+ **Internship at <a href= "http://www.instat-mali.org/" target = "_blank">INSTAT-MALI/ Mali</a>**  
Updating and cleaning data on Malian companies, learning R and VBA.

## Teaching

No teaching for now.

## Consulting

No consulting for now.

## Computer skills

+ Operating Systems: 30% Windows, 70% Ubuntu

+ Languages: R, Python, C/C++, HTML/CSS, JavaScript, PHP, PostgreSQL/MySQL

+ Applications: LaTeX via Miktex, Markdown via Pandoc, databases (e.g. MySQL, Git and SVN for version control

## Languages

+ Bambara: native speaker

+ English: Intermediate level

+ French: native speaker

+ Deutch: beginner